### PR TITLE
Use Unicode.Scalar initializer for most character definitions

### PR DESCRIPTION
**Pull request by erikkerber**
## Description

To resolve a drastic degradation in compiling optimized Swift code using, as is present in **Constants.swift**, thousands of literals, a large conversion to using Character initializers helped the build process at least complete on hardware that is-of-this-world. 

Important to note that any character that required multiple code points, I kept the original escaped String sequence.

## Motivation and Context

Issue as described in https://github.com/IBM-Swift/swift-html-entities/issues/50

## How Has This Been Tested?

Unit tests pass, archive completes.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by erikkerber** [comment]
Unfortunately the diff is not going to be particularly friendly if you want to guarantee correctness for literally every entry. There are tests, and they are good tests, but I do not believe they would catch every single mistake.

**Comment by erikkerber** [comment]
@ianpartridge any thoughts on this?

**Comment by pushkarnk** [comment]
Hi @eskerber , can you please sign the CLA?

**Comment by erikkerber** [comment]
@pushkarnk I signed it a while ago. The bot is not working.

**Comment by pushkarnk** [comment]
@eskerber Thanks for submitting this pull request! I can see that this change is working around an apparent Swift compiler issue and giving us a considerable performance boost. I am just curious to know if the compiler limitation is around "managing constants" or "handling constants in a dictionary". If the limitation is about constants in a dictionary, is it worth writing an embarrassingly long switch statement to map the Strings to Characters? If it is about managing constants overall, I don't think we can do much. 

Eager to know your views!

**Comment by erikkerber** [comment]
@pushkarnk I posted the SR I created for this in the referenced issue:

https://bugs.swift.org/browse/SR-10209

It is a performance regression in Swift 5 optimizations that the team is investigating. I imagine they will fix this in relatively short order (even though that means waiting for a new Swift/Xcode release), so I wouldn't necessarily spend too much time gutting the current implementation.

It's difficult to know exactly if whatever inlining is being held up is simply a result of how many literals there are vs them being in a dictionary. For what it's worth, I did try to break up the dictionaries into a series of dictionary merges 4-5 key/value pairs at a time and it was still slow.

**Comment by pushkarnk** [comment]
There's no harm in accepting this PR as a work-around for a serious performance problem with the swift compiler. We must revisit this problem once there is a resolution for SR-10209.

**Comment by pushkarnk** [comment]
@eskerber The branch has conflicts. If you could rebase it, I'll go ahead and merge this.

**Comment by pushkarnk** [comment]
Hi @eskerber , just wanted to check if you could rebase your branch against the latest master. We can get this merged. Thanks!

**Comment by erikkerber** [comment]
Sorry - usually spend my time in enterprise Github

Rebased 👍

**Comment by pushkarnk** [comment]
Oh, the failures seem to be Travis issues. We're seeing them on other repos too.

**Comment by ianpartridge** [comment]
Yes @djones6 and I know what the problem is.  Will fix ASAP.

**Comment by pushkarnk** [comment]
Hi @djones6 , @eskerber has signed the CLA but the bot doesn't seem to report so. Can you please advise what we could do here?

**Comment by ianpartridge** [comment]
Can we test whether the slow compilation is still a problem in Swift 5.0.1?  I know there were some optimizer performance fixes included in 5.0.1 so if the problem in the compiler is fixed that would make this PR moot?

**Comment by brentleyjones** [comment]
I believe it was still an issue when we checked.

**Comment by erikkerber** [comment]
The fix was cherry-picked into 5.1.

https://bugs.swift.org/browse/SR-10209?focusedCommentId=46236&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-46236

**Comment by ianpartridge** [comment]
OK thanks for checking.  Let's release this 👍

**Comment by ianpartridge** [comment]
https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.13

**Pull request merged**
