### PR TITLE
Don't depend on Foundation since Swift 4.2

### PR DESCRIPTION
**Pull request by broadwaylamb**
## Description

Before Swift 4.2 the `hasSuffix(_:)` method of `String` was unavailable on non-Darwin platforms without importing Foundation.
In Swift 4.2 this was fixed.

## Motivation and Context
This allows us to not depend on Foundation on newer versions of Swift at all.

## How Has This Been Tested?
See the CI results.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by broadwaylamb** [comment]
@ianpartridge do I need to do anything else for this to be landed?

**Comment by broadwaylamb** [comment]
The test failure seems weird, I think it's unrelated.

**Comment by ianpartridge** [comment]
Thanks for the PR! Agreed about the Travis failure, it's a spurious one.

**Review by ianpartridge — APPROVED** [review]

**Comment by ianpartridge** [comment]
Released https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.14 - thanks!

**Pull request merged**
