### PR TITLE
Migrate to Swift 4.0

### PR DESCRIPTION
**Pull request by rlwimi**
Thanks for sharing this work! This PR is for informational purposes. I haven't done any critical thinking about the appropriateness of this resolution of the lone migration issue, so I'm not going to worry about signing a CLA right now. Please close the PR as soon as you're ready.

## Description

This PR migrates the repo to Swift 4. It's a breaking change, so I've bumped the major version number. I've done my best to update docs to reflect both version changes.

## Motivation and Context

There's no logged issue at this time of writing, but the framework is broken in Swift 4. `reference` is a `Substring`, and compilation fails [here](https://github.com/IBM-Swift/swift-html-entities/blob/88efc76d45195162d35104fff5ad1af1d29e6460/Sources/HTMLEntities/String%2BHTMLEntities.swift#L465) with 
```Cannot subscript a value of type '[String : Character]' with an index of type 'Substring'```

## How Has This Been Tested?

Running `swift test` still fails for me, but it's claiming ["method 'defaultTestSuite' was used as a property; add () to call it"](https://github.com/IBM-Swift/swift-html-entities/blob/88efc76d45195162d35104fff5ad1af1d29e6460/Tests/HTMLEntitiesTests/LinuxSafeguardTest.swift#L33), indicating `swift test` is [running Swift 3](https://developer.apple.com/documentation/xctest/xctestcase/1496289-defaulttestsuite?changes=latest_minor), even though I've used `xcode-select` and verified `swift --version` indicates Swift 4. There is probably something I'm missing causing it to test with Swift 3.

In an Xcode project from `swift package generate-xcodeproj`, the existing tests pass after this migration to Swift 4. [Major Input](https://github.com/rlwimi/major-input) depends on [swift-html-entities] and has successfully migrated to Swift 4 using these changes.

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by youming-lin** [comment]
@rlwimi Thanks for looking into this.

On the running in Swift 3 issue, this is due to the Package manifest being in Swift 3 syntax instead of Swift 4 syntax. `swift test` looks at `Package.swift` and builds the source code in either Swift 3.2 or Swift 4 mode depending on the contents of the file.

I'll open an issue to track the Swift 4 migration work.

Edit:
For more info on the Package manifest and how it affects the Swift version, check here:
https://github.com/apple/swift-evolution/blob/master/proposals/0152-package-manager-tools-version.md#impact-on-existing-code

Building the current code with Swift 4 toolchain fits into this row:

| Swift Tools | Swift Tools Version | Swift Language Compatibility Version | Language Version Used |
| --- | --- | --- | --- |
| 4.0 | Not Present | Not Present | Manifest: 3 Sources: 3 |

**Comment by rlwimi** [comment]
Aha! Thanks for the explanation and pointers, @youming-lin!

**Comment by youming-lin** [comment]
I did some testing and uploaded a Swift 4 branch here: https://github.com/IBM-Swift/swift-html-entities/tree/swift-4

With this change the source code will only compile on Swift 4 toolchain, in Swift 4 mode. Will merge once Swift 4 GAs and we decide if we want to add `#if` statements to support 3.1 backward compatibility.

**Comment by youming-lin** [comment]
I have merged in changes to support Swift 4. As we have decided to support both 3.1.1 and 4.0 to maintain backwards compatibility, I've added a `Package@swift-4.0.swift` that is only used by Swift 4 and added Swift version compiler checks in the source code.

**Pull request closed without merging**
